### ISSUE TITLE
Adding items to existing feed

### ISSUE THREAD

**Issue by iojjjjiiii** [egorsmkv/rfeed#1]
I'm not seeing it in the documentation (and I'm not that good to be able to figure it out from the code), but once a feed is generated and the feed.rss() string is saved into an external file (to be published), is there a way to load that file back into a Feed container, add additional items, and re-save feed.rss()?

**Comment by SuperSonicHub1** [comment]
@iojjjjiiii rfeed is designed only for RSS feed generation, not parsing, so no an RSS feed cannot be read, converted into a Feed object, and them modified. If you want this to be added, take it up with the project author and not the creator of a fork: https://github.com/svpino/rfeed
